---
version: '3.9'
services:
  frontend:
    build: ./src/frontend/blog
    ports: 
      - "3000:3000"
    volumes:
      - ./src/frontend/blog:/app/
      - ./src/frontend/blog/node_modules:/app/node_modules/
  backend:
    build: ./src/backend
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports: 
      - "8000:8000"
    volumes:
      - ./src/backend/src:/backend/src/