---
version: '3.9'
services:
  frontend:
    build: ./src/frontend/blog
    ports: 
      - "3000:3000"
    # volumes:
    #   - react:/app/src
  backend:
    build: ./src/backend
    ports: 
      - "8000:8000"
    # volumes:
    #   - python:/app/src
volumes:
  react:
  python: