---
version: '3.9'
services:
  frontend:
    build: ./src/frontend/blog
    ports: 
      - "3000:3000"
    volumes:
      - ./src/frontend/blog:/app/
      - ./src/frontend/blog/node_modules:/app/node_modules/
    environment:
      CHOKIDAR_USEPOLLING: "true"
  backend:
    build: ./src/backend
    ports: 
      - "8000:8000"
    volumes:
      - ./src/backend/src:/backend/src/